[package]
name = "day_18"
version = "0.1.0"
authors = ["C3Suryansu <39475196+C3Suryansu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8"
rand = "0.5.5"